[spaceship]
max_level = 50
next_level_score = 50
gun_max_cap = 30
gun_max_speed = 85

[aliens]
limit = 1
health = 2
speed = 3
gun_speed = 35
gun_power = 1

[stars] 
limit = 15
speed = 50

[health_kit]
health = 2
speed = 3
max_kits = 5
start_with = 1
