[spaceship]
health = 5
max_level = 10

[gun]
limit = 7
speed = 40
power = 3

[aliens]
limit = 1
health = 7
speed = 4

[stars] 
limit = 15
speed = 50

[health_drop]
health = 6
speed = 3
limit = 1
max_drop = 5
start = 1
