[spaceship]
health = 20
max_level = 50
next_level_score = 50
gun_max_cap = 17
gun_cap = 2
gun_speed = 35
gun_max_speed = 80
gun_power = 1

[aliens]
limit = 1
health = 2
speed = 4
gun_speed = 35
gun_power = 1

[stars] 
limit = 15
speed = 50

[health_drop]
health = 2
speed = 3
limit = 1
max_drop = 5
start = 1
