[spaceship]
health = 15
max_level = 10
next_level_score = 500
gun_max_cap = 15
gun_cap = 5
gun_speed = 40
gun_max_speed = 70
gun_power = 2

[aliens]
limit = 1
health = 5
speed = 3
gun_speed = 35
gun_power = 1

[stars] 
limit = 15
speed = 50

[health_drop]
health = 6
speed = 3
limit = 1
max_drop = 5
start = 1
